name: Publish site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        hub config --global hub.protocol https
        hub config --global user.name $user_name
        hub config --global user.email $user_email
        hub remote set-url origin https://$token:x-oauth-basic@github.com/$org/$repo_name.git
        hub remote set-url origin https://$token:x-oauth-basic@github.com/$org/$repo_name.git
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        org: 'IndentStudios'
        repo_name: 'website'
        token: ${{ secrets.WEBSITE_ACTION_TOKEN }}
